# hash:sha256:79c9d9e9eb4fccb27bab6eeb2df9f998c607fcd90fc53a9c77bcb9c0c032dc64
FROM registry.codeocean.com/codeocean/miniconda3:4.12.0-python3.9-ubuntu20.04

ARG DEBIAN_FRONTEND=noninteractive

RUN pip3 install -U --no-cache-dir \
    pandas==2.0.0 \
    sklearn==0.0 \
    matplotlib==3.5.1
